- hosts: ISPConfig
  tasks:
    - name: upgrade all packages and kernel
      yum:
        name: '*'
        state: latest

    - name: Reboot machine to complete kernel update
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: wait for 10 seconds
      pause:
        seconds: 10

    - name: wait for the system to reboot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 60

    - name: Install wget
      yum:
        name: 'wget'
        state: latest

    - name: Download Remi Repos
      get_url: 
         url: "{{ urls }}"
         dest: /home/ansible
      vars:
        urls:
        - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        - "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"

    - name: Install Remi Repos
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - /home/ansible/remi-release-7.rpm
        - /home/ansible/epel-release-latest-7.noarch.rpm

    - name: Remove remi downloaded repo files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/ansible/remi-release-7.rpm
        - /home/ansible/epel-release-latest-7.noarch.rpm

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: latest

    - name: Activate remi-php74 Repos
      command: yum-config-manager --enable remi-php74

    - name: Update packages again
      yum:
        name: '*'
        state: latest
        exclude: kernel*

    - name: Install Remi PHP 7.4
      yum:
        name: php74
        state: latest